"""
Method for exploratory data analysis of a target column including 
summary statistics and distribution visualization.
"""

def eda(data, target_col):
    """
    Generate summary statistics and a histogram for a specified column.

    This function calculates descriptive statistics (mean, count, std, etc.)
    for a target variable and creates a visual distribution plot to identify
    skewness, outliers, or patterns in the data

    Parameters
    ----------
    data : pandas.DataFrame
        The input dataframe containing the features and target values
    target_col : str
        The name of the column to be analyzed for statistics and 
        distribution. Must exist within the provided dataset

    Returns
    -------
    pandas.DataFrame
        A table of summary statistics for the specified column, 
        generated by pandas.Series.describe

    matplotlib.axes.Axes
        The plot object for the histogram, generated by 
        data[target_col].plot(kind='hist')
    Raises
    ------
    KeyError
        If `target_column` is not found in the `dataset` columns.
    TypeError
        If `dataset` is not a valid pandas DataFrame or similar object.
    """
    # 1. Summary stats table (df[target_column].describe())
    # 2. Histogram plot (df[target_column].hist())