"""
Exploratory data analysis of a target column including 
summary statistics and distribution visualization.
"""

def eda(X, y):
    """
    Generate summary statistics and a histogram for a specified column.

    This function calculates descriptive statistics (mean, count, std, etc.)
    for a target variable and creates a visual distribution plot to identify
    skewness, outliers, or patterns in the data

    Parameters
    ----------
    X : pandas.DataFrame
        The input dataframe containing the features and target values
    y : str
        The name of the column to be analyzed for statistics and 
        distribution. Must exist within the provided dataset

    Returns
    -------
    pandas.DataFrame
        A table of summary statistics for the specified column, 
        generated by pandas.Series.describe

    matplotlib.axes.Axes
        The plot object for the histogram, generated by 
        X[y].plot(kind='hist')
    Raises
    ------
    KeyError
        If `y` is not found in the `dataset` columns
    TypeError
        If `X` is not a valid pandas DataFrame or similar object
    """

    import pandas as pd
    import matplotlib.pyplot as plt
    from pandas.api.types import is_numeric_dtype 

    if not isinstance(X, pd.DataFrame):
        raise TypeError(f"Input X has type {type(X)}, must be a pandas DataFrame")

    if not isinstance(y, str):
        raise TypeError(f"Target column name y has type {type(y)}, must be a string")

    if y not in X.columns:
        raise KeyError(f"Column '{y}' not found in DataFrame. Columns in the data: {list(X.columns)}")

    if X[y].empty:
        raise ValueError(f"Column '{y}' is empty (length=0) and can't be analyzed")

    if X[y].dropna().empty:
        raise ValueError(f"Column '{y}' contains only missing values (NaNs)")

    if not is_numeric_dtype(X[y]):
        raise TypeError(f"Column '{y}' has datatype {X[y].dtype} but must be numeric to generate a histogram")


    summary_stats = X[y].describe()
    histogram = X[y].plot(kind="hist")

    return summary_stats, histogram
